export const CURRENCY_ALIASES: Record<string, readonly string[]> = {
  USD: ["$", "usd", "us dollar", "dollar", "dollars"],
  EUR: ["€", "eur", "euro", "euros"],
  GBP: ["£", "gbp", "pound", "pounds", "sterling"],
  JPY: ["¥", "jpy", "yen"],
  CNY: ["cny", "yuan", "renminbi"],
  KRW: ["krw", "won"],
  INR: ["inr", "rupee", "rupees"],
  RUB: ["rub", "ruble", "rubles"],
  AUD: ["aud", "australian dollar"],
  CAD: ["cad", "canadian dollar"],
  CHF: ["chf", "swiss franc"],
  HKD: ["hkd", "hong kong dollar"],
  SGD: ["sgd", "singapore dollar"],
  NZD: ["nzd", "new zealand dollar"],
  MXN: ["mxn", "mexican peso"],
  BRL: ["brl", "brazilian real"],
  ZAR: ["zar", "rand"],
  SEK: ["sek", "swedish krona"],
  NOK: ["nok", "norwegian krone"],
  DKK: ["dkk", "danish krone"],
  PLN: ["pln", "zloty"],
  CZK: ["czk", "czech koruna"],
  HUF: ["huf", "forint"],
  TRY: ["try", "turkish lira"],
  ILS: ["ils", "shekel"],
  PHP: ["php", "peso", "philippine peso"],
  THB: ["thb", "baht"],
  MYR: ["myr", "ringgit"],
  IDR: ["idr", "rupiah"],
  ISK: ["isk", "icelandic krona"],
  RON: ["ron", "leu"]
};
