#!/usr/bin/env sh
set -e

staged_files=$(git diff --cached --name-only --diff-filter=ACMR -- '*.js' '*.jsx' '*.mjs' '*.cjs' '*.ts' '*.tsx' '*.json' '*.html')

[ -z "$staged_files" ] && exit 0

old_ifs=$IFS
IFS='
'
for file in $staged_files; do
  bunx prettier --write "$file"
  git add "$file"
done
IFS=$old_ifs
